// Pages

export const HOMEPAGE_LOADED = 'HOMEPAGE_LOADED'
export const HOMEPAGE_UNLOADED = 'HOMEPAGE_UNLOADED'
export const JAMLIST_PAGE_LOADED = 'JAMLIST_PAGE_LOADED'
export const JAMLIST_PAGE_UNLOADED = 'JAMLIST_PAGE_UNLOADED'
export const JAM_PAGE_LOADED = 'JAMLIST_PAGE_LOADED'
export const JAM_PAGE_UNLOADED = 'JAMLIST_PAGE_UNLOADED'

// User

export const VALIDATE_USERNAME = 'VALIDATE_USERNAME'
export const VALIDATE_PASSWORD = 'VALIDATE_PASSWORD'
export const REGISTER_NEW_USER = 'REGISTER_NEW_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CHOOSE_INSTRUMENT = 'CHOOSE_INSTRUMENT'
export const SWITCH_INSTRUMENT = 'SWITCH_INSTRUMENT'

// JamRoom

export const LIST_ROOMS = 'LIST_ROOMS'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const PREVIEW_ROOM = 'PREVIEW_ROOMS'
export const CREATE_ROOM = 'CREATE_ROOM'
export const ENTER_ROOM = 'ENTER_ROOM'
export const LEAVE_ROOM = 'LEAVE_ROOM'
export const DISPLAY_ROOM_SETTINGS = 'DISPLAY_ROOM_SETTINGS'
export const DISPLAY_ROOM_USERS = 'DISPLAY_ROOM_USERS'
export const SET_JAM_BPM = 'SET_JAM_BPM'
export const SET_JAM_TITLE = 'SET_JAM_TITLE'
export const SET_JAM_DESCRIPTION = 'SET_JAM_DESCRIPTION'

// Instrument

export const CREATE_INSTRUMENT = 'CREATE_INSTRUMENT'
export const START_INSTRUMENT = 'START_INSTRUMENT'
export const STOP_INSTRUMENT = 'STOP_INSTRUMENT'
export const PAUSE_INSTRUMENT = 'PAUSE_INSTRUMENT'

// Sequence

export const EDIT_SEQUENCE = 'EDIT_SEQUENCE'
export const CLEAR_SEQUENCE = 'CLEAR_SEQUENCE'

// Arrangement

export const ADD_SEQUENCE_TO_ARRANGEMENT = 'ADD_SEQUENCE_TO_ARRANGEMENT'
export const REMOVE_SEQUENCE_FROM_ARRANGEMENT =
  'REMOVE_SEQUENCE_FROM_ARRANGEMENT'

// Message

export const POST_MESSAGE = 'POST_MESSAGE'
export const EDIT_MESSAGE = 'EDIT_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
