export const IO_CONNECT = 'connect'
export const IO_DISCONNECT = 'disconnect'

export const IO_CLIENT_JOIN_ROOM = 'IO_CLIENT_JOIN_ROOM'
export const IO_SERVER_JOIN_ROOM = 'IO_SERVER_JOIN_ROOM'

export const IO_CLIENT_LEAVE_ROOM = 'IO_CLIENT_LEAVE_ROOM'
export const IO_SERVER_LEAVE_ROOM = 'IO_SERVER_LEAVE_ROOM'

export const IO_CLIENT_SEND_MESSAGE = 'IO_CLIENT_SEND_MESSAGE'
export const IO_SERVER_SEND_MESSAGE = 'IO_SERVER_SEND_MESSAGE'

export const IO_CLIENT_CHOOSE_INSTRUMENT = 'IO_CLIENT_CHOOSE_INSTRUMENT'
export const IO_SERVER_CHOOSE_INSTRUMENT = 'IO_SERVER_CHOOSE_INSTRUMENT'

export const IO_CLIENT_EDIT_SEQUENCE = 'IO_CLIENT_EDIT_SEQUENCE'
export const IO_SERVER_ADJUST_MIXER = 'IO_CLIENT_ADJUST_MIXER'

export const IO_CLIENT_ADJUST_CUTOFF = 'IO_CLIENT_ADJUST_CUTOFF'
export const IO_SERVER_ADJUST_CUTOFF = 'IO_SERVER_ADJUST_CUTOFF'

export const IO_CLIENT_ADJUST_RESONANCE = 'IO_CLIENT_ADJUST_RESONANCE'
export const IO_SERVER_ADJUST_RESONANCE = 'IO_SERVER_ADJUST_RESONANCE'

export const IO_CLIENT_MUTE_CHANNEL = 'IO_CLIENT_MUTE_CHANNEL'
export const IO_SERVER_MUTE_CHANNEL = 'IO_SERVER_MUTE_CHANNEL'

export const IO_CLIENT_TOGGLE_PLAYBACK = 'IO_CLIENT_TOGGLE_PLAYBACK'
export const IO_SERVER_TOGGLE_PLAYBACK = 'IO_SERVER_TOGGLE_PLAYBACK'
